NET:
    NET_TYPE: "resnet"
TRAIN:
    TRAIN_DATASET_PATH: 'dataset/rsna-pneumonia-detection-challenge/train_images_512'
    TRAIN_LABEL_PATH: 'dataset/rsna-pneumonia-detection-challenge/balanced_labels.csv'
    SAVE_PATH: 'training_results/test_run6'
    N_EPOCH: 200
    LR: 0.0001
    LOSS_PERIOD: 100
    MINI_BATCH_SIZE: 8
    SAVING_EPOCH: 1
    LOAD_CHECKPOINT: 1
VALIDATION:
    USE_VALIDATION: 1
    VALIDATION_PERIOD: 500
TEST:
    TEST_DATASET_PATH: 'dataset/rsna-pneumonia-detection-challenge/test_images_512'
    TEST_LABEL_PATH: 'dataset/rsna-pneumonia-detection-challenge/test_labels.csv'
    WEIGHT_PATH: 'models'
MLFLOW:
    LOG_WEIGHTS: 0
PACKAGING:
    MLFLOW_PYFUNC_MODEL_PATH: 'api'
